# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Fry-Lib-CDBI-Basic
version:      0.05
version_from: lib/Fry/Lib/CDBI/Basic.pm
installdirs:  site
requires:
    Class::Data::Global:           0.01
    Fry::Shell:                    0.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
